new_globals = {
  '_',
	"wm",

	-- awm
	"awn",
	"awm_clock_pulse",
	"awm_normal_input",
	"awm_update_density",

	-- arcan
	"TYPE_FRAMESERVER",
	"TD_HINT_IGNORE",
	"LAUNCH_INTERNAL",
	"FILTER_NONE",
	"FONT_PT_SZ",
	"MASK_UNPICKABLE",
	"VPPCM",
	"VRESW",
	"VRESH",
	"CLOCK",
	"APPLID",

	"switch_default_texfilter",
	"image_surface_properties",
	"mouse_tick",
	"target_displayhint",
	"mouse_add_cursor",
	"mouse_cursor_sf",
	"mouse_iotbl_input",
	"load_image",
	"delete_image",
	"blend_image",
	"move_image",
	"show_image",
	"expire_image",
	"order_image",
	"resize_image",
	"image_inherit_order",
	"image_mask_set",
	"link_image",
	"kbd_repeat",
	"system_load",
	"audio_gain",
	"launch_avfeed",
	"valid_vid",
	"define_nulltarget",
	"target_alloc",
	"image_surface_resolve_properties",
	"color_surface",
	"shutdown",
	"system_collapse",
	"target_input",
	"image_sharestorage",
	"null_surface",
	"resize_video_canvas",
	"video_displaymodes",

	-- ipc
	"zap_resource",
	"open_nonblock",
	"timer_add_periodic",
}
exclude_files = { '**/.*' }