new_globals = {
  '_',
	"wm",

	-- lunawm
	"lunawm",
	"lunawm_clock_pulse",
	"lunawm_normal_input",
	"lunawm_update_density",
	"lunawm_input",
	"VRES_AUTORES",
	"RENDERTARGET_DETACH",
	"RENDERTARGET_SCALE",

	-- arcan
	"TYPE_FRAMESERVER",
	"TD_HINT_IGNORE",
	"TD_HINT_UNFOCUSED",
	"LAUNCH_INTERNAL",
	"FILTER_NONE",
	"FONT_PT_SZ",
	"MASK_UNPICKABLE",
	"VPPCM",
	"VRESW",
	"VRESH",
	"CLOCK",
	"APPLID",
	"WORLDID",
	"BADID",
	"ANCHOR_UR",
	"ANCHOR_UL",
	"ANCHOR_LL",
	"FORMAT_PNG_FLIP",
	"FORMAT_PNG",

	"switch_default_texfilter",
	"image_surface_properties",
	"image_color",
	"image_inherit_order",
	"image_mask_set",
	"image_hit",
	"image_sharestorage",
	"image_surface_resolve_properties",
	"image_set_txcos_default",
	"image_storage_properties",
	"image_scale_txcos",
	"image_surface_resolve",
	"mouse_tick",
	"target_displayhint",
	"mouse_setup",
	"mouse_add_cursor",
	"mouse_cursor_sf",
	"mouse_iotbl_input",
	"mouse_xy",
	"mouse_switch_cursor",
	"mouse_show",
	"mouse_hide",
	"mouse_addlistener",
	"mouse_droplistener",
	"mouse_custom_cursor",
	"load_image",
	"delete_image",
	"blend_image",
	"move_image",
	"show_image",
	"expire_image",
	"order_image",
	"resize_image",
	"link_image",
	"hide_image",
	"nudge_image",
	"rotate_image",
	"kbd_repeat",
	"system_load",
	"audio_gain",
	"launch_avfeed",
	"valid_vid",
	"define_nulltarget",
	"color_surface",
	"shutdown",
	"system_collapse",
	"target_input",
	"target_fonthint",
	"target_alloc",
	"target_updatehandler",
	"null_surface",
	"resize_video_canvas",
	"video_displaymodes",
	"fill_surface",
	"rendertarget_noclear",
	"load_image_asynch",
	"resource",
	"launch_target",
	"accept_target",
	"save_screenshot",
	"alloc_surface",
	"define_recordtarget",

 	"render_text",

	-- ipc
	"zap_resource",
	"open_nonblock",
	"timer_add_periodic",
}
exclude_files = { '**/.*' }